-- Run in Supabase SQL editor

create table if not exists public.levels (
  level_id text primary key,
  name text not null,
  sort_order int not null
);

insert into public.levels (level_id, name, sort_order)
values
  ('level-1', 'Nivel 1', 1),
  ('level-2', 'Nivel 2', 2),
  ('level-3', 'Nivel 3', 3),
  ('level-4', 'Nivel 4', 4),
  ('level-5', 'Nivel 5', 5)
on conflict (level_id) do nothing;

create table if not exists public.patients (
  patient_id bigint primary key,
  unique_code text not null unique,
  name text not null,
  age int not null,
  registration_date timestamptz not null default now(),
  current_level_id text references public.levels(level_id),
  status text not null default 'active',
  streak_count int not null default 0,
  last_completed_date date
);

create table if not exists public.diagnostics (
  diagnostic_id bigint primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  diagnostic_number int not null,
  diagnostic_date timestamptz not null default now(),
  max_inspiratory_volume int not null
);

create table if not exists public.patient_levels (
  patient_level_id bigint primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  level_id text not null references public.levels(level_id),
  diagnostic_id bigint not null references public.diagnostics(diagnostic_id) on delete cascade,
  target_volume int not null,
  level_status text not null,
  sessions_completed int not null default 0,
  perfect_sessions_completed int not null default 0,
  sessions_completed_today int not null default 0,
  last_session_date timestamptz
);

create table if not exists public.sessions (
  session_id bigint primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  patient_level_id bigint not null references public.patient_levels(patient_level_id) on delete cascade,
  level_id text not null references public.levels(level_id),
  session_date timestamptz not null default now(),
  session_number int not null default 1,
  total_attempts int not null,
  valid_attempts int not null,
  invalid_attempts int not null,
  completed boolean not null default true,
  perfect_session boolean not null default false,
  compliance_percent int not null default 0,
  max_volume int not null default 0,
  avg_volume int not null default 0,
  avg_hold_seconds numeric not null default 0,
  perfect boolean not null default false,
  interrupted boolean not null default false
);

create table if not exists public.attempts (
  attempt_id bigint primary key,
  session_id bigint not null references public.sessions(session_id) on delete cascade,
  attempt_number int not null default 1,
  volume_reached int not null default 0,
  hold_time int not null default 0,
  is_valid boolean not null default false,
  attempt_timestamp timestamptz not null default now(),
  hold_ms int not null default 0,
  peak_volume int not null default 0,
  valid boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_progress (
  daily_progress_id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  progress_date date not null,
  sessions_completed int not null default 0,
  perfect_sessions_completed int not null default 0,
  daily_goal_completed boolean not null default false,
  streak_count int not null default 0,
  unique (patient_id, progress_date)
);

create table if not exists public.consent_records (
  consent_id bigint generated by default as identity primary key,
  patient_id bigint references public.patients(patient_id) on delete cascade,
  accepted_at timestamptz not null,
  document_version text not null,
  app_version text,
  consent_accepted boolean not null default true,
  consent_status text not null default 'active',
  accepted_terms boolean not null default false,
  accepted_consent boolean not null default false,
  accepted_privacy boolean not null default false,
  accepted_clinical_disclaimer boolean not null default false,
  accepted_support_indicators_disclaimer boolean not null default false,
  document_title text,
  acceptance_method text not null default 'digital_in_app',
  accepted_statements jsonb not null default '[]'::jsonb,
  withdrawn_at timestamptz
);

alter table public.patients enable row level security;
alter table public.diagnostics enable row level security;
alter table public.patient_levels enable row level security;
alter table public.sessions enable row level security;
alter table public.attempts enable row level security;
alter table public.daily_progress enable row level security;
alter table public.consent_records enable row level security;

drop policy if exists "Prototype open access" on public.patients;
create policy "Prototype open access" on public.patients for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.diagnostics;
create policy "Prototype open access" on public.diagnostics for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.patient_levels;
create policy "Prototype open access" on public.patient_levels for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.sessions;
create policy "Prototype open access" on public.sessions for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.attempts;
create policy "Prototype open access" on public.attempts for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.daily_progress;
create policy "Prototype open access" on public.daily_progress for all using (true) with check (true);
drop policy if exists "Prototype open access" on public.consent_records;
create policy "Prototype open access" on public.consent_records for all using (true) with check (true);

